language: python
install:
  - pip install .
script: python -m unittest discover tests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "BdR4ukvPuHWTqXV+TQrF6wLBZzA6V/NblJXu5ZXMNjLKd82it2dloNwJ/iIfUWJTR6rpctI6dybecIjc6CldBLJEC0wvuzGnX2gnJ0VBPuIfgBQpI1EF5Fz/Eqjeh+HMc/SiGe4RaFtuxUSiATnR8oY/L5EYFd37k8w/D5KpS4WHanEZ1jrrDJJEdej+Bv/dxX0ny1d2Wcwjrc6bLe5uGTGIIMmZRtVKegG6wIuTanLXKWnk7izNkUuDsdW0SqZydr5Ytn2q/6uKNx8J4/qBmWPuCoy8d+Klu/gGticDdprj/0DTtCwRX2TiFmjyIcs+0j3eImfB5nUP8vE2xR7pmUzczxQT5vI4ErZlYIPaDAUEj4ZhVr660puDaD8eCHgPQnFYn9bOyDJPlJWd5iHPTE+mnwwkErZfMxfDCrx1rXaOWAjORfqiNNZSSym6fBIMBmeNutHh0caVYoeCZ8DLkHZDDPdV0AVve4BziY/Y2hmYQ91GGs64333HMVHzxKeHgO5Q2ZTst7sDR0hlWlczsu/S9ijNklUkCoMYiU4XWu0oWJiW6ByytK36Q5+AZc80d4V8oNhYcN5IyBTYJmflBBo8txFyDqzCAbWw42s/L+CKIMpnUXfVbdqTyDiOMJoSH23F5iAzM52oKPQ7YELxMRo518MGX68zrBT1E+2tweM="
  on:
    tags: true
